### ISSUE TITLE
supportsave

### ISSUE THREAD

**Issue by capirexlefou** [brocade/pyfos#13]
When the supportsave.py is executed the script fails with the following error:

Traceback (most recent call last):
  File "supportsave.py", line 200, in <module>
    main(sys.argv[1:])
  File "supportsave.py", line 194, in main
    ss_show_status(session, ss_rsp_obj)
  File "supportsave.py", line 161, in ss_show_status
    _get_supportsave_status(session, ss_req_obj, ss_rsp_obj)
  File "supportsave.py", line 125, in _get_supportsave_status
    while ("in-Progress" in ss_state or "Queued" in ss_state or
TypeError: argument of type 'NoneType' is not iterable

I found out that the _post_supportsave() function is never executed.

Any idea on how to resolve this issue?

Thanks in advance.

Best Regards,
Cherif Amghar

**Comment by capirexlefou** [comment]
When run the script in debug mode i have this message : 

{'info-code': -1, 'info-message': 'Switch version is lower than the object', 'info-type': 'Informational'}

the switch is running the version of FOS 8.2.1a

**Comment by capirexlefou** [comment]
Even with the script failing, the supportsave is triggered and runssuccessfully against the switch.
