### ISSUE TITLE
Python complaining __init__.py file,  Pls help 

### ISSUE THREAD

**Issue by cindyhu11** [brocade/pyfos#8]
I installed pyfos on my windows machine.   whenever I try to use the modules (either run as script or import as module), Python alway complain about the __init__.py file.  
>>> import pyfos.utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\python\python3.6.6\pyfos\pyfos\utils\__init__.py", line 1
    ../__init__.py
    ^

**Comment by daniel-chung-broadcom** [comment]
are you able to share how you install pyfos and details of your env?

**Comment by cindyhu11** [comment]
Hi,

I use pip to install pyfos:
pip3 install --user pyfos

My python is 3.6.6   is the version supported ?

What other information you need ?

Cindy Hu
Senior SAN Storage Admin
Office: 416-496-7215,  3337215 | Cell: 647-385-6793 | cindy.hu@sunlife.com | 2255 Sheppard Ave East , Willowdale , Ontario, M2J 4Y1

**Comment by daniel-chung-broadcom** [comment]
Can you please also share when you executed pip3? Also, what pyfos version do you see on your installed README? We did make some changes between 1.2.0 and 1.2.1. So, we want to clarify which version is being used. 

Pyfos is tested with 3.5.2. I suspect that 3.6.6 should be ok. But it is difficult confirm one way or another without proper testing.

**Comment by cindyhu11** [comment]
Pyfos 1.2.1

And I installed on Windows 2012 server. It should be ok, right?

The __init__.py file under the main directory .\pyfos  is ok. It complains the syntax of __init__.py file under subdirectory. Can I just empty __init__.py file under subdirectory ?  it looks like all it does is point to the __init__.py file under the main directory.

Cindy Hu
Senior SAN Storage Admin
Office: 416-496-7215,  3337215 | Cell: 647-385-6793 | cindy.hu@sunlife.com | 2255 Sheppard Ave East , Willowdale , Ontario, M2J 4Y1

**Comment by daniel-chung-broadcom** [comment]
I don't personally use window env for python dev. So, I really cannot say. I followed up with some folks who does and they are not having issues with __init__.py when executing them. In my linux env, I don't have any issues with __init__.py. 

I guess you can try emptying out the file since the content is mostly related to version stamp. Let me know if that works ok. I'll keep you posted on what I find out here as well.

**Comment by daniel-chung-broadcom** [comment]
I just installed python 3.8.0 on windows 10. I did "pip install --user pyfos". Then I python and "import pyfos.utils" and I just get a next prompt back. Is this along the line of what you are doing?
